//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedCheetah.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisersRequest
    {
        public int Id { get; set; }
        public string companyName { get; set; }
        public string companyAddress { get; set; }
        public string companyPhone { get; set; }
        public Nullable<int> Industry { get; set; }
        public string emailAddress { get; set; }
        public string ContactPersonsPhoneNumber { get; set; }
        public int status { get; set; }
        public string statusMessage { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int TryCount { get; set; }
    }
}
