//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedCheetah.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelPartnersRequest
    {
        public int Id { get; set; }
        public string BusinessName { get; set; }
        public string ContactPerson { get; set; }
        public string ContactAddress { get; set; }
        public string phoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> totalDailyWalkInCustomers { get; set; }
        public Nullable<int> averageDailyWalkInCustomers { get; set; }
        public int Status { get; set; }
        public string StatusMessage { get; set; }
        public int requestType { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> MsgDeliveredTimeStamp { get; set; }
        public Nullable<int> NatureOfBusiness { get; set; }
        public int TryCount { get; set; }
    }
}
