//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedCheetah.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelPartnerUsers_old
    {
        public int UserId { get; set; }
        public string ApplicationId { get; set; }
        public string FirstName { get; set; }
        public string OtherName { get; set; }
        public string LastName { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string StreetAddress { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> UserStatus { get; set; }
        public int KYCUpload { get; set; }
        public string Password { get; set; }
        public string PasswordReset { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
