//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedCheetah.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelPartnerUsers_18thMay2018
    {
        public int UserId { get; set; }
        public string ApplicationId { get; set; }
        public string BusinessName { get; set; }
        public string FirstName { get; set; }
        public string OtherName { get; set; }
        public string LastName { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string StreetAddress { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> UserStatus { get; set; }
        public int KYCUpload { get; set; }
        public string KYCRemarks { get; set; }
        public string KYC_ID_Path { get; set; }
        public string KYC_Utility_Path { get; set; }
        public string Password { get; set; }
        public string PasswordReset { get; set; }
        public int PaymentStatus { get; set; }
        public string VCode { get; set; }
        public int ApplicationProgress { get; set; }
        public Nullable<int> ApplicationStatus { get; set; }
        public int DeliveryMethodId { get; set; }
        public Nullable<int> PickUpLocationId { get; set; }
        public string Signature { get; set; }
        public Nullable<int> ReferralQuestionResponse { get; set; }
        public Nullable<int> ReferralOption { get; set; }
        public string ReferralValueDesc { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
