//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedCheetah.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUsRequest
    {
        public int RequestId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Message { get; set; }
        public int Status { get; set; }
        public string StatusMessage { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<System.DateTime> MessageSentTimestamp { get; set; }
        public int TryCount { get; set; }
    }
}
