//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedCheetah.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryMethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryMethod()
        {
            this.ChannelPartnerUsers = new HashSet<ChannelPartnerUser>();
        }
    
        public int Id { get; set; }
        public string Location { get; set; }
        public int IsVisible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChannelPartnerUser> ChannelPartnerUsers { get; set; }
        public virtual DeliveryMethod DeliveryMethod1 { get; set; }
        public virtual DeliveryMethod DeliveryMethod2 { get; set; }
    }
}
