//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedCheetah.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickUpLocation
    {
        public int Id { get; set; }
        public string PickUpLoc { get; set; }
        public string PickUpAddress { get; set; }
        public int IsVisible { get; set; }
    }
}
