//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedCheetah.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RC_MODEMS_BKP_050718
    {
        public int MODEM_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public int ACCOUNT_ID { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public int LOCATION_ID { get; set; }
        public string IMSI { get; set; }
        public string IP_ADDRESS { get; set; }
    }
}
