//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedCheetah.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referral
    {
        public string RefereeName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string ReferralCode { get; set; }
        public System.DateTime DateReferred { get; set; }
        public string ReferrerName { get; set; }
    }
}
