//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedCheetah.Core.DB.SWIFTUTILITY.STAGING
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiometricsBonusService
    {
        public int ID { get; set; }
        public string PaymentTable { get; set; }
        public Nullable<int> StartRow { get; set; }
        public Nullable<int> EndRow { get; set; }
        public Nullable<System.DateTime> LastRun { get; set; }
    }
}
